// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGlJq9hQtGyjcpw33i_ounRqHCkH0eHo',
    appId: '1:343399507394:web:c8d9453fb581ca2d0a625b',
    messagingSenderId: '343399507394',
    projectId: 'fire-flutter-bb422',
    authDomain: 'fire-flutter-bb422.firebaseapp.com',
    storageBucket: 'fire-flutter-bb422.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2qkShHJKiXm3GRFs_mtrj09IfyHPNOw',
    appId: '1:343399507394:android:53ac0ab2bb922ef50a625b',
    messagingSenderId: '343399507394',
    projectId: 'fire-flutter-bb422',
    storageBucket: 'fire-flutter-bb422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Xufcb4Bd4TWoh1PJS0JOpaOILofvLLw',
    appId: '1:343399507394:ios:cbd4ddc37437a3f00a625b',
    messagingSenderId: '343399507394',
    projectId: 'fire-flutter-bb422',
    storageBucket: 'fire-flutter-bb422.appspot.com',
    iosClientId: '343399507394-0vqfr36n5jsf11fi5ur5re6dtljqb7cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Xufcb4Bd4TWoh1PJS0JOpaOILofvLLw',
    appId: '1:343399507394:ios:cbd4ddc37437a3f00a625b',
    messagingSenderId: '343399507394',
    projectId: 'fire-flutter-bb422',
    storageBucket: 'fire-flutter-bb422.appspot.com',
    iosClientId: '343399507394-0vqfr36n5jsf11fi5ur5re6dtljqb7cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat',
  );
}
